version: '2'

services:
  proxy:
      build: ./proxy
      user: root
      volumes: 
        - ./proxy:/code
        - ./logs:/var/log/erss
      command: bash -c "./proxy"
      ports:
        - "12345:12345"